//! Small authored pixel silhouettes, shaded by the renderer at runtime.
pub const GRUNT: &[&str] = &[
    "       ssssss       ",
    "      sHHHHHHs      ",
    "      HaaaaaHs      ",
    "      HEEEEEEH      ",
    "      saDDDass      ",
    "   ssssaDDasssss   ",
    "  sHHHaHHHHaHHHs  ",
    " sHaDaHHHHHHaDaHs ",
    " sHDDaHaEEaHaDDHs ",
    " sHDDaHaEEaHaDDHs ",
    "  aDDsaHHHHasDDa  ",
    "  aDDsaDDDDasDDa  ",
    "  sDDsaHHHHasDDs  ",
    "  ssssHHHHHHssss  ",
    "      aDaDaDa      ",
    "     sHDsDHDs     ",
    "     sHDs HHDs    ",
    "     sHDs sHDs    ",
    "     sHDs sHDs    ",
    "    sHHHs sHHHs   ",
    "    sssss sssss   ",
];
pub const RUNNER: &[&str] = &[
    "          ss       ",
    "        sHHa       ",
    "       sHHHa       ",
    "       HEEEa       ",
    "       sDDs        ",
    "      sHHHHs       ",
    "    saHHaHHa       ",
    "   saDaHEHaDa      ",
    "  saDs HHa sDa     ",
    "  sDDs HHa  sDa    ",
    "   ss saDas  sDs   ",
    "      HHHHa   ss   ",
    "     sHDsHDs       ",
    "    sHDs sHDs      ",
    "   sHDs   sHDs     ",
    "   HHa     sHDs    ",
    "   HHa      sHa    ",
    "   sHa      sHa    ",
    "  sHHs      sHHs   ",
    "  ssss      ssss   ",
];
pub const BRUTE: &[&str] = &[
    "      sssssss      ",
    "     sHHHHHHHs     ",
    "     HaaaaaaaH     ",
    "     HEEEEEEEH     ",
    " ssssaDDDDDassss   ",
    "sHHHHHHHHHHHHHHHs ",
    "HaaaHaHHHHHaHaaaH ",
    "HDDDHaaEEEaaHDDDH ",
    "HDDDHaaEEEaaHDDDH ",
    "sDDDHaaaaaaaHDDDs ",
    "sDDDsHHHHHHHsDDDs ",
    "sDDDsaDDDDDAsDDDs ",
    "sDDDsaHHHHHasDDDs ",
    "sssssHHHHHHHsssss ",
    "    HaaDsDaaH     ",
    "    HDDDsDDDH     ",
    "    HDDD DDDH     ",
    "    HDDD DDDH     ",
    "   sHHHH HHHHs    ",
    "   sssss sssss    ",
];

pub const SHOTGUN: &[&str] = &[
    "             ssssss ssssss              ",
    "            sHHHHHHsHHHHHHs             ",
    "            HsDDDDHsHsDDDDH             ",
    "            HsDDDDHsHsDDDDH             ",
    "            aHaaaHasHaHHHHa             ",
    "            aHDDDHasHaDDDHa             ",
    "           saHDDDHasHaDDDHs             ",
    "           saHDDDHasHaDDDHs             ",
    "          ssHHHHHHHHHHHHHHss            ",
    "         sHHaaaaaaaaaaaaaaaHs           ",
    "         HaaDDDDDDDDDDDDDDDaHs          ",
    "        sHaDDDHHHHHHHHHHDDDDaHs         ",
    "        HaaDDDHEEEEHaaaHDDDDDaHs        ",
    "       sHaDDDDHHHHHHaaaHDDDDDDaHs       ",
    "      ssHaaDDDDDDDDDDDDDDDDDDaaHs      ",
    "    ssGGGHHaaaaaaaaaaaaaaaaaHHDDDs      ",
    "   sGGggGGGHHHHHHHHHHHHHHHHHDDDDDss    ",
    "  sGGggggGGGssDDDDDDDDDDDDDDDDsGGGGs   ",
    " sGGggggGGGsssDDDDDDDDDDDDDDDsGggGGGs  ",
    "saaaaaaaGGss  sDDDDDDDDDDDDDsGGgggGGGs ",
    "aEEEEEEaaGs   sDDDDDDDDDDDDDsGGgggGGGs ",
    "aaaaaaaaass   sDDDDDDDDDDDDDssaaaaaaaas",
];
